### ISSUE TITLE
Python (3.7) is throwing an error when attempting to install this package via Yarn in Windows

### ISSUE THREAD

**Issue by boveus** [ArkEcosystem/ark-client#111]
**Describe the bug**
When I run ` yarn add arkecosystem/javascript-cli` it fails.  I have installed the most current release versions of Yarn, Node, and Python

**To Reproduce**
1. Install the current versions of Yarn, Node, and Python (3.7)
2. Run `yarn add arkecosystem/javascript-cli`.  

**Expected behavior**
The package should install without error *or* there should be a dependency of the older version of Python that this package requires to run.

**Screenshots**
This is the error:
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Brandon\AppData\Local\Programs\Python\Python37-32\python.EXE -c impor
t sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Brandon\node_modules\node-hid
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Server (please complete the following information):**
 - OS:  Windows 10 64-bit

**Additional context**
I am also using Git Bash to run this command (I am not sure if that introduces a problem or not).

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
