### ISSUE TITLE
The contributor guidelines are incorrect

### ISSUE THREAD

**Issue by boveus** [ArkEcosystem/ark-client#112]
**Describe the bug**
It also looks like the link populated in new pull requests needs to be changed from `Please see https://docs.ark.io/docs/contributing for details before opening your pull request.` to `Please see https://docs.ark.io/guidebook/contribution-guidelines/ for details before opening your pull request.`

**To Reproduce**
1. Open a new PR

**Expected behavior**
The contributor guidelines in the PR template should not reference a URL that returns a 404.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
