### ISSUE TITLE
Multisig support

### ISSUE THREAD

**Issue by roccomuso** [ArkEcosystem/ark-client#116]
Does Ark support multisignature?
Any documentation available?
How the tx object will look like?

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
There is no multisignature support but it is coming with 2.6.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
