### ISSUE TITLE
Access Denied: Windows 10

### ISSUE THREAD

**Issue by ritual89** [ArkEcosystem/ark-client#13]
Hey ArkTeam,

Recently on Windows 10 and encountering this issue: 

http://prntscr.com/goljct

Any ideas? I haven't been able to resolve this.

**Comment by alexbarnsley** [comment]
@greggpeacock are you running from command line?

**Edit** maybe try as administrator? I don't have to and I'm on Windows 10, just thought I'd ask.

What's your node and mom version? `npm -v` and `node -v`

**Comment by fix** [comment]
this is a ark-desktop related issue, closing it
