### ISSUE TITLE
Get Ledger working for first address

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/ark-client#24]
Currently a Ledger only works for addresses that have made transactions (through the desktop client, for example). We need to replicate the same functionality as the desktop client, where it shows the next address available when interacting with the ledger. If connected, there should always be at least 1 address available (the first one), used or not.

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/43
