### ISSUE TITLE
Crash if trying to send a transaction from a new account

### ISSUE THREAD

**Issue by rosulucian** [ArkEcosystem/ark-client#25]
We should probably check for (body.account && body.account.secondSignature).

https://github.com/ArkEcosystem/ark-client/blob/9d44ca368ee832e38468924762751b0d3ef4de7b/index.js#L153-L158

Currently it crashes the client.

**Comment by rosulucian** [comment]
Maybe other checks are more appropriate (check for balance, check for account, etc.) here or down the callstack.

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/37
