### ISSUE TITLE
Installation is failing

### ISSUE THREAD

**Issue by avbanks** [ArkEcosystem/ark-client#27]
Hey, I seem to not be able to install the client.  The installer either hangs-up or fails, is anyone else experiencing this issue?

**Comment by alexbarnsley** [comment]
Ah you was the person who slacked me today. Someone else has opened the same issue. It's on the top of my list first thing in the morning

**Comment by avbanks** [comment]
Ok, please let me know how I can assist you in resolving this issue.

**Comment by alexbarnsley** [comment]
@avbanks i've done a PR which fixes it I think (did for me on Ubuntu - i could replicate your issue). If you could check the description of the PR to test, that would be great! PR: #29
