### ISSUE TITLE
App crashes when sending transaction to an invalid address

### ISSUE THREAD

**Issue by CryptologySAC** [ArkEcosystem/ark-client#38]
When you try to send to an address that doesn't exist (ark> account send 1 nonexistingaddress) the program will crash because the error thrown in arkjs isn't handled. For the same reason this also will happen when other arkjs transactions are executed (vote, delegate).

I'll solve this by adding the correct error handling to the code.

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/39
