### ISSUE TITLE
App crashes on a server/VM because the USB port can't initialize.

### ISSUE THREAD

**Issue by CryptologySAC** [ArkEcosystem/ark-client#40]
Ark-client tries to initialize a USB port to check if a Ledger is connected, when no USB port can be initialized the app crashes. On most Virtual Machines (and many servers) there is no USB port available and (in my opinion) that is precisely where a CLI is used most.

I will make a PR that solves this by checking for errors on the USB binding and if any occur notifies the user that Ledger support is not available (and disables Ledger support internally).

**Comment by joshpurvis** [comment]
I can confirm this bug. I ran into it on bare metal. Forgot I had my Ledger plugged in -- it was idle, sitting on my Ethereum wallet. Ran Ark Client (just using a seed, no Ledger wallet yet) for the first time in months, and it was freezing the UI within 2-3 seconds after starting the application.

Environment:
- ArkClient-1.5.1
- Arch Linux

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/41
