### ISSUE TITLE
When connected to Devnet app shows Mainnet accounts on Ledger

### ISSUE THREAD

**Issue by CryptologySAC** [ArkEcosystem/ark-client#42]
When I connect to the devnet and try to send DARK, the app shows my mainnet accounts from my Ledger. The balances show my ARK balances with the DA symbol. 

When I try to send something from one of these accounts I receive an UnHandledPromiseRejectionWarning.

**Comment by CryptologySAC** [comment]
This is caused by forgetting to reset the connection to the Ledger when changing networks. 
- I connected first to the mainnet
- Ledger connected
- connected to devnet
- Ledger kept old information
I'll create a PR to solve this

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/43
