### ISSUE TITLE
Cant discover peers (Devnet) when all 5 servers hardcoded in are down

### ISSUE THREAD

**Issue by CryptologySAC** [ArkEcosystem/ark-client#44]
The client can't connect to the Devnet. All 5 hardcoded servers are currently down and therefor no peers can be discovered. Maybe it's an idea to use the networks module from Arkjs? (which is larger, more up to date and probably better maintained).

**Comment by faustbrian** [comment]
You could try to incorporate https://github.com/ArkEcosystem/ARK-Peers, might be worth waiting for the rewrite though when Core 2.0 comes to devnet.

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/ark-client/pull/50. Will be included in the next release.
