### ISSUE TITLE
vote not working

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-client#7]
function has been left unfinished

**Comment by alexbarnsley** [comment]
@fix I'm about to compile this to test, but thought i'd check first. Is the vote still not working, looks like it posts the transaction here: https://github.com/ArkEcosystem/ark-client/blob/master/index.js#L415

if not then I'll see if I can take a look 👍

**Comment by fix** [comment]
the unfinished part is here: https://github.com/ArkEcosystem/ark-client/blob/master/index.js#L399

it creates an empty vote. It should put as second argument like ["+publicKeyOfDelegate"]

Point is to pass in the vorpal function either the public key either the delegate name. in the latter, you need to perform and api call to get the publicKey of the delegate.

**Comment by alexbarnsley** [comment]
@fix I've raised this in a PR #8

Take a look and let me know if it meets what you're looking for please
